### ISSUE TITLE
Start adding unit tests for moclo assembly app

### ISSUE THREAD

**Issue by Benedict-Carling** [Imperial-iGEM/DJANGO-Assembly-Methods#6]
Hello,

this issue is to start creating the unit tests inside repositry

moclo_assembly/tests/...

we have unit tests set up to run on every pull request and everytime someone runs the command specified in the read me

python manage.py test

I have poorly written some some unit tests for the tests_urls.py file and a single unit test in tests_views.py file, these files or located within basic_assembly/tests folder

how our programme finds unit tests is it looks for folders called tests which contain a init.py file and within files which start with test_... inside there it finds Class which starts with test and runs all "unit test" which are function inside this class which begin with test

A description on how django finds unit tests
https://stackoverflow.com/questions/36546168/how-to-run-all-tests-with-python-manage-py-test-command-in-django

A great youtube series on adding unittest for django
https://www.youtube.com/watch?v=qwypH3YvMKc&list=PLbpAWbHbi5rMF2j5n6imm0enrSD9eQUaM

**Comment by GabrielleJohnston** [comment]
Some tests have been written and are working!
